services:
  gatus:
    image: twinproduction/gatus:v5.33.1
    container_name: gatus
    restart: always
    environment:
      - GATUS_CONFIG_PATH=/config
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./config-dev:/config
    networks:
      - web
    depends_on:
      - postgres

  swag:
    image: linuxserver/swag:5.1.0
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=999               
      - PGID=988               
      - TZ=Europe/London
      - URL=status-dev-openstack.stfc.ac.uk
      - VALIDATION=http      
      - EMAIL=CLOUD-SUPPORT@stfc.ac.uk
    volumes:
      - ./swag-config/dev-status.subdomain.conf:/config/nginx/proxy-confs/dev-status.subdomain.conf
      - swag-data:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    depends_on:
      - gatus

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - web

volumes:
  pgdata:
  swag-data:

networks:
  web:
